### ISSUE TITLE
Multi-response generation

### ISSUE THREAD

**Issue by xdcui-nlp** [thu-spmi/damd-multiwoz#6]
path='experiments/all_multi_acts_sample3_sd666_lr0.005_bs80_sp5_dc3'
python model.py -mode test -cfg cuda_device=0 eval_load_path=$path aspn_decode_mode=beam beam_diverse_param=0.2 beam_width=5 nbest=5
**The following error will occur：**
RuntimeError: Trying to create tensor with negative dimension -471: [1, -471]

Does anyone know how to solve it？

**Comment by 594zyc** [comment]
Hi @AdienQ,

Could you please provide more information about the error? Thanks

**Comment by xdcui-nlp** [comment]
**The complete error information is as follows:**
Traceback (most recent call last):
  File "model.py", line 517, in <module>
    main()
  File "model.py", line 512, in main
    m.eval(data='test')
  File "model.py", line 306, in eval
    decoded = self.m(inputs, hidden_states, first_turn, mode='test')
  File "/opt/current-env/anaconda3/envs/tf_2.x/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/special/user/root/damd-multiwoz-master/damd_net.py", line 972, in forward
    decoded = self.test_forward(inputs, hidden_states, first_turn)
  File "/home/special/user/root/damd-multiwoz-master/damd_net.py", line 1108, in test_forward
    hs, decoded = self.beam_decode('aspn', usdx_enc_last_h, first_turn, inputs, hs, decoded)
  File "/home/special/user/root/damd-multiwoz-master/damd_net.py", line 1301, in beam_decode
    zeros = cuda_(torch.zeros(1, cfg.max_span_length - len(decode_idx)).long())
RuntimeError: Trying to create tensor with negative dimension -471: [1, -471]

**Comment by 594zyc** [comment]
I cannot reproduce the bug from my side. From the error log, it seems that the `decode_idx` is longer than `max_span_length` which should not be the case. Are you using Python 3.6 and PyTorch 1.0?

**Comment by xdcui-nlp** [comment]
It may be because of the version，I am using Python 3.8 and PyTorch 1.8
